---
# yamllint disable rule:comments
# yamllint disable rule:truthy
name: Pre-commit Code Quality Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: ghcr.io/${{ github.repository }}-pre-commit:main

    if: github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Cache Pre-commit
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit|${{ github.repository }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Cache Terraform/OpenTofu providers
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: $HOME/.terraform.d/plugin-cache
          key: tf-providers-${{ hashFiles('**/*.tf*') }}
          restore-keys: |
            tf-providers-

      - name: Set Terraform plugin cache
        run: echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >> $GITHUB_ENV

      - name: Mark repository as safe
        shell: bash
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run pre-commit in all files
        shell: bash
        run: pre-commit run --show-diff-on-failure --color=always --all-files | tee pre-commit.log
